//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkHome.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Creds : global::System.Configuration.ApplicationSettingsBase {
        
        private static Creds defaultInstance = ((Creds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Creds())));
        
        public static Creds Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("440000000000:3302")]
        public string AppApiBasicAuth {
            get {
                return ((string)(this["AppApiBasicAuth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webdev:FenyCKbVsdVRQBf2")]
        public string WebApiBasicAuth {
            get {
                return ((string)(this["WebApiBasicAuth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api-key:2_Ua7jVDxk291udlLRiZ0Q5856")]
        public string AddressIoAuth {
            get {
                return ((string)(this["AddressIoAuth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("536fc3c409075b")]
        public string IpInfoKey {
            get {
                return ((string)(this["IpInfoKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("440000000000:3302")]
        public string AppApiBasicAuthGBP {
            get {
                return ((string)(this["AppApiBasicAuthGBP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3570000000000:8596")]
        public string AppApiBasicAuthEUR {
            get {
                return ((string)(this["AppApiBasicAuthEUR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000000000:8009")]
        public string AppApiBasicAuthUSD {
            get {
                return ((string)(this["AppApiBasicAuthUSD"]));
            }
        }
    }
}
