//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkHome.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class URIs : global::System.Configuration.ApplicationSettingsBase {
        
        private static URIs defaultInstance = ((URIs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URIs())));
        
        public static URIs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/login")]
        public string Authenticate {
            get {
                return ((string)(this["Authenticate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/resetpassword/start")]
        public string ResetPasswordRequest {
            get {
                return ((string)(this["ResetPasswordRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/resetpassword/confirm")]
        public string ResetPasswordConfirm {
            get {
                return ((string)(this["ResetPasswordConfirm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/resetpassword/change")]
        public string NewPassword {
            get {
                return ((string)(this["NewPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thm/standard/international/destinations")]
        public string Destination {
            get {
                return ((string)(this["Destination"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thm/nonuseraccount/international/top")]
        public string MobileTopRates {
            get {
                return ((string)(this["MobileTopRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/tha/nonuseraccount/international/top")]
        public string TalkHomeAppTopRates {
            get {
                return ((string)(this["TalkHomeAppTopRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thcc/nonuseraccount/minutes/top")]
        public string CallingCardsTopMinutes {
            get {
                return ((string)(this["CallingCardsTopMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/history/call")]
        public string CallHistoryPage {
            get {
                return ((string)(this["CallHistoryPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/history/call/totalpages")]
        public string CallHistoryTotalPages {
            get {
                return ((string)(this["CallHistoryTotalPages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/useraccount/summary")]
        public string AccountSummary {
            get {
                return ((string)(this["AccountSummary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/signup")]
        public string SignUp {
            get {
                return ((string)(this["SignUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/sim/order/new")]
        public string MailOrder {
            get {
                return ((string)(this["MailOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thcc/nonuseraccount/minutes/all")]
        public string CallingCardsMinutes {
            get {
                return ((string)(this["CallingCardsMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/tha/nonuseraccount/international/all")]
        public string TalkHomeAppRates {
            get {
                return ((string)(this["TalkHomeAppRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thm/nonuseraccount/uk/all")]
        public string TalkHomeMobileUKRates {
            get {
                return ((string)(this["TalkHomeMobileUKRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thm/nonuseraccount/international/all")]
        public string TalkHomeMobileInternationalRates {
            get {
                return ((string)(this["TalkHomeMobileInternationalRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/useraccount/summary")]
        public string AccountDetails {
            get {
                return ((string)(this["AccountDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/history/payment")]
        public string PaymentHistoryPage {
            get {
                return ((string)(this["PaymentHistoryPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/history/payment/totalpages")]
        public string PaymentHistoryTotalPages {
            get {
                return ((string)(this["PaymentHistoryTotalPages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/confirm")]
        public string VerifySignUpEmail {
            get {
                return ((string)(this["VerifySignUpEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/rates/thm/nonuseraccount/roaming/all")]
        public string TalkHomeMobileRoamingRates {
            get {
                return ((string)(this["TalkHomeMobileRoamingRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/website/in-app-details")]
        public string GetAppUserByMsisdn {
            get {
                return ((string)(this["GetAppUserByMsisdn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/th/merchant/getcustomer")]
        public string GetCustomer {
            get {
                return ((string)(this["GetCustomer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/talkhome/product")]
        public string AddProduct {
            get {
                return ((string)(this["AddProduct"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/useraccount/address")]
        public string SaveAppUserBillingAddress {
            get {
                return ((string)(this["SaveAppUserBillingAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/th/payment/start")]
        public string StartPayment {
            get {
                return ((string)(this["StartPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/th/payment/retrieve")]
        public string PaymentRetrieve {
            get {
                return ((string)(this["PaymentRetrieve"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/th/merchant/oneclick")]
        public string OneClickCheckout {
            get {
                return ((string)(this["OneClickCheckout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/th/payment/oneclickstatus")]
        public string OneClickRetrieve {
            get {
                return ((string)(this["OneClickRetrieve"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/promotional")]
        public string PromoSignUp {
            get {
                return ((string)(this["PromoSignUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/voucher/add")]
        public string RedeemVoucher {
            get {
                return ((string)(this["RedeemVoucher"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/redeempoints")]
        public string ReedemPoints {
            get {
                return ((string)(this["ReedemPoints"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Bundle/SetBundleAutoRenewal")]
        public string AutoRenewBundles {
            get {
                return ((string)(this["AutoRenewBundles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/set/credit/autorenewal")]
        public string AutoRenewTopUp {
            get {
                return ((string)(this["AutoRenewTopUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/update/address/home")]
        public string UpdateAddressHome {
            get {
                return ((string)(this["UpdateAddressHome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/update/address/billing")]
        public string UpdateAddressBilling {
            get {
                return ((string)(this["UpdateAddressBilling"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/update/address/shipping")]
        public string UpdateAddressShipping {
            get {
                return ((string)(this["UpdateAddressShipping"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/destinations1")]
        public string TalkHomeAppInternationalRates {
            get {
                return ((string)(this["TalkHomeAppInternationalRates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Sim/CreditSimRequest")]
        public string CreditSimOrder {
            get {
                return ((string)(this["CreditSimOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Sim/CreditSimPayment")]
        public string CreditSimPayment {
            get {
                return ((string)(this["CreditSimPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Sim/CreditSimFullfilment\n")]
        public string CreditSimFullfilment {
            get {
                return ((string)(this["CreditSimFullfilment"]));
            }
        }
    }
}
