//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BannerButton</summary>
	[PublishedContentModel("bannerButton")]
	public partial class BannerButton : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bannerButton";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BannerButton(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BannerButton, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BackgroundImage
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public IPublishedContent BackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("backgroundImage"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Description Calling Card
		///</summary>
		[ImplementPropertyType("descriptionCallingCard")]
		public IHtmlString DescriptionCallingCard
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionCallingCard"); }
		}

		///<summary>
		/// Height: in px
		///</summary>
		[ImplementPropertyType("height")]
		public string Height
		{
			get { return this.GetPropertyValue<string>("height"); }
		}

		///<summary>
		/// LaptopBackgroundImage
		///</summary>
		[ImplementPropertyType("laptopBackgroundImage")]
		public IPublishedContent LaptopBackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("laptopBackgroundImage"); }
		}

		///<summary>
		/// Layout
		///</summary>
		[ImplementPropertyType("layout")]
		public string Layout
		{
			get { return this.GetPropertyValue<string>("layout"); }
		}

		///<summary>
		/// MobileBackgroundImage
		///</summary>
		[ImplementPropertyType("mobileBackgroundImage")]
		public IPublishedContent MobileBackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("mobileBackgroundImage"); }
		}

		///<summary>
		/// TargetType
		///</summary>
		[ImplementPropertyType("targetType")]
		public string TargetType
		{
			get { return this.GetPropertyValue<string>("targetType"); }
		}

		///<summary>
		/// TargetUrl
		///</summary>
		[ImplementPropertyType("targetUrl")]
		public Umbraco.Web.Models.RelatedLinks TargetUrl
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("targetUrl"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public IHtmlString Title
		{
			get { return this.GetPropertyValue<IHtmlString>("title"); }
		}

		///<summary>
		/// Title Calling Card
		///</summary>
		[ImplementPropertyType("titleCallingCard")]
		public IHtmlString TitleCallingCard
		{
			get { return this.GetPropertyValue<IHtmlString>("titleCallingCard"); }
		}

		///<summary>
		/// WidgetName
		///</summary>
		[ImplementPropertyType("widgetName")]
		public string WidgetName
		{
			get { return this.GetPropertyValue<string>("widgetName"); }
		}
	}
}
