//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>CallingCardsBenefits</summary>
	[PublishedContentModel("callingCardsBenefits")]
	public partial class CallingCardsBenefits : PublishedContentModel, IMetaProperties, IOffers
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "callingCardsBenefits";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CallingCardsBenefits(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CallingCardsBenefits, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BenefitsHeading
		///</summary>
		[ImplementPropertyType("benefitsHeading")]
		public string BenefitsHeading
		{
			get { return this.GetPropertyValue<string>("benefitsHeading"); }
		}

		///<summary>
		/// BenefitsImage
		///</summary>
		[ImplementPropertyType("benefitsImage")]
		public IPublishedContent BenefitsImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("benefitsImage"); }
		}

		///<summary>
		/// BenefitsImage1
		///</summary>
		[ImplementPropertyType("benefitsImage1")]
		public IPublishedContent BenefitsImage1
		{
			get { return this.GetPropertyValue<IPublishedContent>("benefitsImage1"); }
		}

		///<summary>
		/// BenefitsText
		///</summary>
		[ImplementPropertyType("benefitsText")]
		public Newtonsoft.Json.Linq.JToken BenefitsText
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("benefitsText"); }
		}

		///<summary>
		/// BenefitsText1
		///</summary>
		[ImplementPropertyType("benefitsText1")]
		public Newtonsoft.Json.Linq.JToken BenefitsText1
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("benefitsText1"); }
		}

		///<summary>
		/// Call To Action
		///</summary>
		[ImplementPropertyType("callToAction")]
		public Umbraco.Web.Models.RelatedLinks CallToAction
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("callToAction"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// EarnPointsButtons
		///</summary>
		[ImplementPropertyType("earnPointsButtons")]
		public Umbraco.Web.Models.RelatedLinks EarnPointsButtons
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("earnPointsButtons"); }
		}

		///<summary>
		/// PointsDescription
		///</summary>
		[ImplementPropertyType("pointsDescription")]
		public Newtonsoft.Json.Linq.JToken PointsDescription
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("pointsDescription"); }
		}

		///<summary>
		/// PointsText
		///</summary>
		[ImplementPropertyType("pointsText")]
		public string PointsText
		{
			get { return this.GetPropertyValue<string>("pointsText"); }
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("text")]
		public string Text
		{
			get { return this.GetPropertyValue<string>("text"); }
		}

		///<summary>
		/// Meta description: Enter the SEO description.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta image: Upload and crop the image for link previews.
		///</summary>
		[ImplementPropertyType("metaImage")]
		public Umbraco.Web.Models.ImageCropDataSet MetaImage
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaImage(this); }
		}

		///<summary>
		/// Meta tags: Enter the SEO meta tags.
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTags(this); }
		}

		///<summary>
		/// Meta title: Enter the {title} tag content.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTitle(this); }
		}

		///<summary>
		/// OG Description: Enter the Open Graph tag description.
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetOGdescription(this); }
		}
	}
}
