//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Campaign</summary>
	[PublishedContentModel("campaignBlock")]
	public partial class CampaignBlock : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "campaignBlock";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CampaignBlock(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CampaignBlock, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Campaign code: Eneter a unique code for this campaign (if applicable)
		///</summary>
		[ImplementPropertyType("campaignCode")]
		public string CampaignCode
		{
			get { return this.GetPropertyValue<string>("campaignCode"); }
		}

		///<summary>
		/// Heading: Enter the heading for the campaign.
		///</summary>
		[ImplementPropertyType("campaignHeading")]
		public string CampaignHeading
		{
			get { return this.GetPropertyValue<string>("campaignHeading"); }
		}

		///<summary>
		/// Long description: Enter the long description for the campaign.
		///</summary>
		[ImplementPropertyType("campaignLongDescription")]
		public string CampaignLongDescription
		{
			get { return this.GetPropertyValue<string>("campaignLongDescription"); }
		}

		///<summary>
		/// Main sub-title: Enter a sub-title (if applicable).
		///</summary>
		[ImplementPropertyType("campaignMainSubtitle")]
		public string CampaignMainSubtitle
		{
			get { return this.GetPropertyValue<string>("campaignMainSubtitle"); }
		}

		///<summary>
		/// Main title: Enter the main title of the campaign.
		///</summary>
		[ImplementPropertyType("campaignMainTitle")]
		public string CampaignMainTitle
		{
			get { return this.GetPropertyValue<string>("campaignMainTitle"); }
		}

		///<summary>
		/// Link: Enter a link (if applicable).
		///</summary>
		[ImplementPropertyType("link")]
		public Umbraco.Web.Models.RelatedLinks Link
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("link"); }
		}
	}
}
