//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Custom Page</summary>
	[PublishedContentModel("customPage")]
	public partial class CustomPage : PublishedContentModel, IMetaProperties, IRelatedFaqs5, IURlalias
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Campaign: Select a Campaign (if applicable).
		///</summary>
		[ImplementPropertyType("customPageCampaign")]
		public IPublishedContent CustomPageCampaign
		{
			get { return this.GetPropertyValue<IPublishedContent>("customPageCampaign"); }
		}

		///<summary>
		/// customPage Campaign 2: Select a second Campaign (if applicable).
		///</summary>
		[ImplementPropertyType("customPageCampaign2")]
		public IPublishedContent CustomPageCampaign2
		{
			get { return this.GetPropertyValue<IPublishedContent>("customPageCampaign2"); }
		}

		///<summary>
		/// Important information: Enter content for the important information block (if applicable).
		///</summary>
		[ImplementPropertyType("importantInformation")]
		public IHtmlString ImportantInformation
		{
			get { return this.GetPropertyValue<IHtmlString>("importantInformation"); }
		}

		///<summary>
		/// Important information, sidebar: Enter the content for the sidebar of important information (if applicable).
		///</summary>
		[ImplementPropertyType("importantInformationSidebar")]
		public IHtmlString ImportantInformationSidebar
		{
			get { return this.GetPropertyValue<IHtmlString>("importantInformationSidebar"); }
		}

		///<summary>
		/// Intro: Enter an introduction to the page (if appplicable).
		///</summary>
		[ImplementPropertyType("intro")]
		public IHtmlString Intro
		{
			get { return this.GetPropertyValue<IHtmlString>("intro"); }
		}

		///<summary>
		/// Page title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public IHtmlString PageTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("pageTitle"); }
		}

		///<summary>
		/// Meta description: Enter the SEO description.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta image: Upload and crop the image for link previews.
		///</summary>
		[ImplementPropertyType("metaImage")]
		public Umbraco.Web.Models.ImageCropDataSet MetaImage
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaImage(this); }
		}

		///<summary>
		/// Meta tags: Enter the SEO meta tags.
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTags(this); }
		}

		///<summary>
		/// Meta title: Enter the {title} tag content.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTitle(this); }
		}

		///<summary>
		/// OG Description: Enter the Open Graph tag description.
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetOGdescription(this); }
		}

		///<summary>
		/// FAQ 1: Select the first FAQ.
		///</summary>
		[ImplementPropertyType("fAQ1")]
		public IPublishedContent FAq1
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq1(this); }
		}

		///<summary>
		/// FAQ 2: Select the second FAQ.
		///</summary>
		[ImplementPropertyType("fAQ2")]
		public IPublishedContent FAq2
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq2(this); }
		}

		///<summary>
		/// FAQ 3: Select the third FAQ.
		///</summary>
		[ImplementPropertyType("fAQ3")]
		public IPublishedContent FAq3
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq3(this); }
		}

		///<summary>
		/// FAQ 4: Select the fourth FAQ.
		///</summary>
		[ImplementPropertyType("fAQ4")]
		public IPublishedContent FAq4
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq4(this); }
		}

		///<summary>
		/// Alias: Enter the alias, if needed. Can be a comma-separated list.
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return Umbraco.Web.PublishedContentModels.URlalias.GetUmbracoUrlAlias(this); }
		}
	}
}
