//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>FeatureBox</summary>
	[PublishedContentModel("featureBox")]
	public partial class FeatureBox : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "featureBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FeatureBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeatureBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BackgroundColor: Hexidecimal value (eg: #ffffff)
		///</summary>
		[ImplementPropertyType("backgroundColor")]
		public string BackgroundColor
		{
			get { return this.GetPropertyValue<string>("backgroundColor"); }
		}

		///<summary>
		/// FontColor: Hexidecimal value (#ffffff)
		///</summary>
		[ImplementPropertyType("fontColor")]
		public string FontColor
		{
			get { return this.GetPropertyValue<string>("fontColor"); }
		}

		///<summary>
		/// Full Width
		///</summary>
		[ImplementPropertyType("fullWidth")]
		public bool FullWidth
		{
			get { return this.GetPropertyValue<bool>("fullWidth"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Intelligence
		///</summary>
		[ImplementPropertyType("intelligence")]
		public string Intelligence
		{
			get { return this.GetPropertyValue<string>("intelligence"); }
		}

		///<summary>
		/// IntelligenceDefaultHeading
		///</summary>
		[ImplementPropertyType("intelligenceDefaultHeading")]
		public IHtmlString IntelligenceDefaultHeading
		{
			get { return this.GetPropertyValue<IHtmlString>("intelligenceDefaultHeading"); }
		}

		///<summary>
		/// Intelligence Default Text
		///</summary>
		[ImplementPropertyType("intelligenceDefaultText")]
		public IHtmlString IntelligenceDefaultText
		{
			get { return this.GetPropertyValue<IHtmlString>("intelligenceDefaultText"); }
		}

		///<summary>
		/// Intelligence Heading
		///</summary>
		[ImplementPropertyType("intelligenceHeading")]
		public IHtmlString IntelligenceHeading
		{
			get { return this.GetPropertyValue<IHtmlString>("intelligenceHeading"); }
		}

		///<summary>
		/// Intelligence Text
		///</summary>
		[ImplementPropertyType("intelligenceText")]
		public IHtmlString IntelligenceText
		{
			get { return this.GetPropertyValue<IHtmlString>("intelligenceText"); }
		}

		///<summary>
		/// IsTopUp
		///</summary>
		[ImplementPropertyType("isTopUp")]
		public bool IsTopUp
		{
			get { return this.GetPropertyValue<bool>("isTopUp"); }
		}

		///<summary>
		/// TargetUrl
		///</summary>
		[ImplementPropertyType("targetUrl")]
		public Umbraco.Web.Models.RelatedLinks TargetUrl
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("targetUrl"); }
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("text")]
		public IHtmlString Text
		{
			get { return this.GetPropertyValue<IHtmlString>("text"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public IHtmlString Title
		{
			get { return this.GetPropertyValue<IHtmlString>("title"); }
		}

		///<summary>
		/// TopUpProduct
		///</summary>
		[ImplementPropertyType("topUpProduct")]
		public string TopUpProduct
		{
			get { return this.GetPropertyValue<string>("topUpProduct"); }
		}
	}
}
