//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>CallingCardsHome</summary>
	[PublishedContentModel("home1")]
	public partial class Home1 : PublishedContentModel, IMetaProperties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Calling Cards link: enter the Calling Cards link.
		///</summary>
		[ImplementPropertyType("callingCardsLink")]
		public Umbraco.Web.Models.RelatedLinks CallingCardsLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("callingCardsLink"); }
		}

		///<summary>
		/// Calling Cards description: Enter the description of the Calling Cards
		///</summary>
		[ImplementPropertyType("homepageCallingCardsDescription")]
		public string HomepageCallingCardsDescription
		{
			get { return this.GetPropertyValue<string>("homepageCallingCardsDescription"); }
		}

		///<summary>
		/// Talk Home App description: Enter the description for Talk Home App
		///</summary>
		[ImplementPropertyType("homepageTalkHomeAppDescription")]
		public string HomepageTalkHomeAppDescription
		{
			get { return this.GetPropertyValue<string>("homepageTalkHomeAppDescription"); }
		}

		///<summary>
		/// Talk Home Mobile description: Enter the description for Talk Home Mobile
		///</summary>
		[ImplementPropertyType("homepageTalkHomeMobileDescription")]
		public string HomepageTalkHomeMobileDescription
		{
			get { return this.GetPropertyValue<string>("homepageTalkHomeMobileDescription"); }
		}

		///<summary>
		/// Talk Home App link: Enter the Talk Home App link.
		///</summary>
		[ImplementPropertyType("talkHomeAppLink")]
		public Umbraco.Web.Models.RelatedLinks TalkHomeAppLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("talkHomeAppLink"); }
		}

		///<summary>
		/// Talk Home Mobile link: Enter the Talk Home Mobile link
		///</summary>
		[ImplementPropertyType("talkHomeMobileLink")]
		public Umbraco.Web.Models.RelatedLinks TalkHomeMobileLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("talkHomeMobileLink"); }
		}

		///<summary>
		/// Talk Home Products title: Enter the title.
		///</summary>
		[ImplementPropertyType("talkHomeProductsTitle")]
		public string TalkHomeProductsTitle
		{
			get { return this.GetPropertyValue<string>("talkHomeProductsTitle"); }
		}

		///<summary>
		/// Meta description: Enter the SEO description.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta image: Upload and crop the image for link previews.
		///</summary>
		[ImplementPropertyType("metaImage")]
		public Umbraco.Web.Models.ImageCropDataSet MetaImage
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaImage(this); }
		}

		///<summary>
		/// Meta tags: Enter the SEO meta tags.
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTags(this); }
		}

		///<summary>
		/// Meta title: Enter the {title} tag content.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTitle(this); }
		}

		///<summary>
		/// OG Description: Enter the Open Graph tag description.
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetOGdescription(this); }
		}
	}
}
