//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>IntelligentCalls</summary>
	[PublishedContentModel("intelligentCalls")]
	public partial class IntelligentCalls : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "intelligentCalls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IntelligentCalls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IntelligentCalls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Call To Action
		///</summary>
		[ImplementPropertyType("callToAction")]
		public string CallToAction
		{
			get { return this.GetPropertyValue<string>("callToAction"); }
		}

		///<summary>
		/// Call ToAction Background Color
		///</summary>
		[ImplementPropertyType("callToActionBackgroundColor")]
		public string CallToActionBackgroundColor
		{
			get { return this.GetPropertyValue<string>("callToActionBackgroundColor"); }
		}

		///<summary>
		/// Call To Action Color
		///</summary>
		[ImplementPropertyType("callToActionColor")]
		public string CallToActionColor
		{
			get { return this.GetPropertyValue<string>("callToActionColor"); }
		}

		///<summary>
		/// Rates Background Color Even Row
		///</summary>
		[ImplementPropertyType("ratesBackgroundColorEvenRow")]
		public string RatesBackgroundColorEvenRow
		{
			get { return this.GetPropertyValue<string>("ratesBackgroundColorEvenRow"); }
		}

		///<summary>
		/// Rates Background Color Odd Row
		///</summary>
		[ImplementPropertyType("ratesBackgroundColorOddRow")]
		public string RatesBackgroundColorOddRow
		{
			get { return this.GetPropertyValue<string>("ratesBackgroundColorOddRow"); }
		}

		///<summary>
		/// TextColor
		///</summary>
		[ImplementPropertyType("textColor")]
		public string TextColor
		{
			get { return this.GetPropertyValue<string>("textColor"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Title Background Color
		///</summary>
		[ImplementPropertyType("titleBackgroundColor")]
		public string TitleBackgroundColor
		{
			get { return this.GetPropertyValue<string>("titleBackgroundColor"); }
		}

		///<summary>
		/// Title Color
		///</summary>
		[ImplementPropertyType("titleColor")]
		public string TitleColor
		{
			get { return this.GetPropertyValue<string>("titleColor"); }
		}
	}
}
