//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Offer</summary>
	[PublishedContentModel("offer")]
	public partial class Offer : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "offer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Offer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Offer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description: Enter the offer description.
		///</summary>
		[ImplementPropertyType("offerDescription")]
		public string OfferDescription
		{
			get { return this.GetPropertyValue<string>("offerDescription"); }
		}

		///<summary>
		/// Heading: Enter the offer main heading.
		///</summary>
		[ImplementPropertyType("offerHeading")]
		public string OfferHeading
		{
			get { return this.GetPropertyValue<string>("offerHeading"); }
		}

		///<summary>
		/// Sub-heading: Enter the sub-heading for the offer.
		///</summary>
		[ImplementPropertyType("offerSubHeading")]
		public string OfferSubHeading
		{
			get { return this.GetPropertyValue<string>("offerSubHeading"); }
		}
	}
}
