//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1397 with alias "relatedFAQs5"
	/// <summary>Related FAQs (4)</summary>
	public partial interface IRelatedFaqs5 : IPublishedContent
	{
		/// <summary>FAQ 1</summary>
		IPublishedContent FAq1 { get; }

		/// <summary>FAQ 2</summary>
		IPublishedContent FAq2 { get; }

		/// <summary>FAQ 3</summary>
		IPublishedContent FAq3 { get; }

		/// <summary>FAQ 4</summary>
		IPublishedContent FAq4 { get; }
	}

	/// <summary>Related FAQs (4)</summary>
	[PublishedContentModel("relatedFAQs5")]
	public partial class RelatedFaqs5 : PublishedContentModel, IRelatedFaqs5
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "relatedFAQs5";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RelatedFaqs5(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RelatedFaqs5, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FAQ 1: Select the first FAQ.
		///</summary>
		[ImplementPropertyType("fAQ1")]
		public IPublishedContent FAq1
		{
			get { return GetFAq1(this); }
		}

		/// <summary>Static getter for FAQ 1</summary>
		public static IPublishedContent GetFAq1(IRelatedFaqs5 that) { return that.GetPropertyValue<IPublishedContent>("fAQ1"); }

		///<summary>
		/// FAQ 2: Select the second FAQ.
		///</summary>
		[ImplementPropertyType("fAQ2")]
		public IPublishedContent FAq2
		{
			get { return GetFAq2(this); }
		}

		/// <summary>Static getter for FAQ 2</summary>
		public static IPublishedContent GetFAq2(IRelatedFaqs5 that) { return that.GetPropertyValue<IPublishedContent>("fAQ2"); }

		///<summary>
		/// FAQ 3: Select the third FAQ.
		///</summary>
		[ImplementPropertyType("fAQ3")]
		public IPublishedContent FAq3
		{
			get { return GetFAq3(this); }
		}

		/// <summary>Static getter for FAQ 3</summary>
		public static IPublishedContent GetFAq3(IRelatedFaqs5 that) { return that.GetPropertyValue<IPublishedContent>("fAQ3"); }

		///<summary>
		/// FAQ 4: Select the fourth FAQ.
		///</summary>
		[ImplementPropertyType("fAQ4")]
		public IPublishedContent FAq4
		{
			get { return GetFAq4(this); }
		}

		/// <summary>Static getter for FAQ 4</summary>
		public static IPublishedContent GetFAq4(IRelatedFaqs5 that) { return that.GetPropertyValue<IPublishedContent>("fAQ4"); }
	}
}
