//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1339 with alias "relatedOffers"
	/// <summary>Related Offers</summary>
	public partial interface IRelatedOffers : IPublishedContent
	{
		/// <summary>Offer 1</summary>
		IPublishedContent Offer1 { get; }

		/// <summary>Offer 2</summary>
		IPublishedContent Offer2 { get; }

		/// <summary>Offer 3</summary>
		IPublishedContent Offer3 { get; }

		/// <summary>Related Offers title</summary>
		string RelatedOffersTitle { get; }
	}

	/// <summary>Related Offers</summary>
	[PublishedContentModel("relatedOffers")]
	public partial class RelatedOffers : PublishedContentModel, IRelatedOffers
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "relatedOffers";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RelatedOffers(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RelatedOffers, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Offer 1: Select the first offer.
		///</summary>
		[ImplementPropertyType("offer1")]
		public IPublishedContent Offer1
		{
			get { return GetOffer1(this); }
		}

		/// <summary>Static getter for Offer 1</summary>
		public static IPublishedContent GetOffer1(IRelatedOffers that) { return that.GetPropertyValue<IPublishedContent>("offer1"); }

		///<summary>
		/// Offer 2: Select the second offer.
		///</summary>
		[ImplementPropertyType("offer2")]
		public IPublishedContent Offer2
		{
			get { return GetOffer2(this); }
		}

		/// <summary>Static getter for Offer 2</summary>
		public static IPublishedContent GetOffer2(IRelatedOffers that) { return that.GetPropertyValue<IPublishedContent>("offer2"); }

		///<summary>
		/// Offer 3: Select the third offer
		///</summary>
		[ImplementPropertyType("offer3")]
		public IPublishedContent Offer3
		{
			get { return GetOffer3(this); }
		}

		/// <summary>Static getter for Offer 3</summary>
		public static IPublishedContent GetOffer3(IRelatedOffers that) { return that.GetPropertyValue<IPublishedContent>("offer3"); }

		///<summary>
		/// Related Offers title: Enter the title.
		///</summary>
		[ImplementPropertyType("relatedOffersTitle")]
		public string RelatedOffersTitle
		{
			get { return GetRelatedOffersTitle(this); }
		}

		/// <summary>Static getter for Related Offers title</summary>
		public static string GetRelatedOffersTitle(IRelatedOffers that) { return that.GetPropertyValue<string>("relatedOffersTitle"); }
	}
}
