//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>SimLanding</summary>
	[PublishedContentModel("simLanding")]
	public partial class SimLanding : PublishedContentModel, IMetaProperties, IRelatedFaqs5
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "simLanding";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SimLanding(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SimLanding, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Color CSS
		///</summary>
		[ImplementPropertyType("colorCSS")]
		public string ColorCss
		{
			get { return this.GetPropertyValue<string>("colorCSS"); }
		}

		///<summary>
		/// Cost
		///</summary>
		[ImplementPropertyType("cost")]
		public string Cost
		{
			get { return this.GetPropertyValue<string>("cost"); }
		}

		///<summary>
		/// Data
		///</summary>
		[ImplementPropertyType("data")]
		public string Data
		{
			get { return this.GetPropertyValue<string>("data"); }
		}

		///<summary>
		/// Data1
		///</summary>
		[ImplementPropertyType("data1")]
		public string Data1
		{
			get { return this.GetPropertyValue<string>("data1"); }
		}

		///<summary>
		/// Image: Needs to be of the following dimensions 400px (width) 223px (height)
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Minutes
		///</summary>
		[ImplementPropertyType("minutes")]
		public string Minutes
		{
			get { return this.GetPropertyValue<string>("minutes"); }
		}

		///<summary>
		/// Plan
		///</summary>
		[ImplementPropertyType("plan")]
		public string Plan
		{
			get { return this.GetPropertyValue<string>("plan"); }
		}

		///<summary>
		/// Plan Sub Name
		///</summary>
		[ImplementPropertyType("planSubName")]
		public string PlanSubName
		{
			get { return this.GetPropertyValue<string>("planSubName"); }
		}

		///<summary>
		/// Promo Tag Line
		///</summary>
		[ImplementPropertyType("promoTagLine")]
		public string PromoTagLine
		{
			get { return this.GetPropertyValue<string>("promoTagLine"); }
		}

		///<summary>
		/// Texts
		///</summary>
		[ImplementPropertyType("texts")]
		public string Texts
		{
			get { return this.GetPropertyValue<string>("texts"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Meta description: Enter the SEO description.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta image: Upload and crop the image for link previews.
		///</summary>
		[ImplementPropertyType("metaImage")]
		public Umbraco.Web.Models.ImageCropDataSet MetaImage
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaImage(this); }
		}

		///<summary>
		/// Meta tags: Enter the SEO meta tags.
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTags(this); }
		}

		///<summary>
		/// Meta title: Enter the {title} tag content.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTitle(this); }
		}

		///<summary>
		/// OG Description: Enter the Open Graph tag description.
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetOGdescription(this); }
		}

		///<summary>
		/// FAQ 1: Select the first FAQ.
		///</summary>
		[ImplementPropertyType("fAQ1")]
		public IPublishedContent FAq1
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq1(this); }
		}

		///<summary>
		/// FAQ 2: Select the second FAQ.
		///</summary>
		[ImplementPropertyType("fAQ2")]
		public IPublishedContent FAq2
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq2(this); }
		}

		///<summary>
		/// FAQ 3: Select the third FAQ.
		///</summary>
		[ImplementPropertyType("fAQ3")]
		public IPublishedContent FAq3
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq3(this); }
		}

		///<summary>
		/// FAQ 4: Select the fourth FAQ.
		///</summary>
		[ImplementPropertyType("fAQ4")]
		public IPublishedContent FAq4
		{
			get { return Umbraco.Web.PublishedContentModels.RelatedFaqs5.GetFAq4(this); }
		}
	}
}
