//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Welcome</summary>
	[PublishedContentModel("welcome")]
	public partial class Welcome : PublishedContentModel, IBanner, IMetaProperties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "welcome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Welcome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Welcome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Campaign: Select the campaign.
		///</summary>
		[ImplementPropertyType("campaign")]
		public IPublishedContent Campaign
		{
			get { return this.GetPropertyValue<IPublishedContent>("campaign"); }
		}

		///<summary>
		/// Description: Enter a description for the page header.
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetDescription(this); }
		}

		///<summary>
		/// Image: Upload and crop the image.
		///</summary>
		[ImplementPropertyType("image")]
		public Umbraco.Web.Models.ImageCropDataSet Image
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetImage(this); }
		}

		///<summary>
		/// Primary link: Enter a link for the primary Call to action.
		///</summary>
		[ImplementPropertyType("primaryLink")]
		public Umbraco.Web.Models.RelatedLinks PrimaryLink
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetPrimaryLink(this); }
		}

		///<summary>
		/// Secondary link: Enter a link for the secondary Call to action.
		///</summary>
		[ImplementPropertyType("secondaryLink")]
		public Umbraco.Web.Models.RelatedLinks SecondaryLink
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetSecondaryLink(this); }
		}

		///<summary>
		/// Title: Enter the page title.
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetTitle(this); }
		}

		///<summary>
		/// Meta description: Enter the SEO description.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta image: Upload and crop the image for link previews.
		///</summary>
		[ImplementPropertyType("metaImage")]
		public Umbraco.Web.Models.ImageCropDataSet MetaImage
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaImage(this); }
		}

		///<summary>
		/// Meta tags: Enter the SEO meta tags.
		///</summary>
		[ImplementPropertyType("metaTags")]
		public string MetaTags
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTags(this); }
		}

		///<summary>
		/// Meta title: Enter the {title} tag content.
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetMetaTitle(this); }
		}

		///<summary>
		/// OG Description: Enter the Open Graph tag description.
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaProperties.GetOGdescription(this); }
		}
	}
}
