//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkHome.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalkHome.App_LocalResources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string App_help_link_0 {
            get {
                return ResourceManager.GetString("App_help_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string App_help_link_1 {
            get {
                return ResourceManager.GetString("App_help_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string App_help_link_2 {
            get {
                return ResourceManager.GetString("App_help_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up.
        /// </summary>
        public static string Button_0 {
            get {
                return ResourceManager.GetString("Button_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up using Paypal.
        /// </summary>
        public static string Button_1 {
            get {
                return ResourceManager.GetString("Button_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_2 {
            get {
                return ResourceManager.GetString("Button_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Button_3 {
            get {
                return ResourceManager.GetString("Button_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_4 {
            get {
                return ResourceManager.GetString("Button_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Button_5 {
            get {
                return ResourceManager.GetString("Button_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply voucher.
        /// </summary>
        public static string Button_apply_voucher {
            get {
                return ResourceManager.GetString("Button_apply_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make payment.
        /// </summary>
        public static string Button_make_payment {
            get {
                return ResourceManager.GetString("Button_make_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows-1252.
        /// </summary>
        public static string Charset {
            get {
                return ResourceManager.GetString("Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher code.
        /// </summary>
        public static string Form_label_0 {
            get {
                return ResourceManager.GetString("Form_label_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the Terms and Conditions.
        /// </summary>
        public static string Form_label_1 {
            get {
                return ResourceManager.GetString("Form_label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Form_label_10 {
            get {
                return ResourceManager.GetString("Form_label_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string Form_label_11 {
            get {
                return ResourceManager.GetString("Form_label_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string Form_label_12 {
            get {
                return ResourceManager.GetString("Form_label_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Form_label_13 {
            get {
                return ResourceManager.GetString("Form_label_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County/State.
        /// </summary>
        public static string Form_label_14 {
            get {
                return ResourceManager.GetString("Form_label_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string Form_label_15 {
            get {
                return ResourceManager.GetString("Form_label_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Form_label_16 {
            get {
                return ResourceManager.GetString("Form_label_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        public static string Form_label_17 {
            get {
                return ResourceManager.GetString("Form_label_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string Form_label_18 {
            get {
                return ResourceManager.GetString("Form_label_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on card.
        /// </summary>
        public static string Form_label_19 {
            get {
                return ResourceManager.GetString("Form_label_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string Form_label_20 {
            get {
                return ResourceManager.GetString("Form_label_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Number.
        /// </summary>
        public static string Form_label_21 {
            get {
                return ResourceManager.GetString("Form_label_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Form_label_22 {
            get {
                return ResourceManager.GetString("Form_label_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string Form_label_23 {
            get {
                return ResourceManager.GetString("Form_label_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Form_label_24 {
            get {
                return ResourceManager.GetString("Form_label_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Form_label_25 {
            get {
                return ResourceManager.GetString("Form_label_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forename.
        /// </summary>
        public static string Form_label_7 {
            get {
                return ResourceManager.GetString("Form_label_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Form_label_8 {
            get {
                return ResourceManager.GetString("Form_label_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Form_label_9 {
            get {
                return ResourceManager.GetString("Form_label_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit.
        /// </summary>
        public static string Label_add_credit {
            get {
                return ResourceManager.GetString("Label_add_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add voucher.
        /// </summary>
        public static string Label_add_voucher {
            get {
                return ResourceManager.GetString("Label_add_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a top up option.
        /// </summary>
        public static string Label_select_option {
            get {
                return ResourceManager.GetString("Label_select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to verify your account. Return to the home screen and then try again. If the problem persists, please contact our customer service team..
        /// </summary>
        public static string Message_0 {
            get {
                return ResourceManager.GetString("Message_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transaction has been cancelled..
        /// </summary>
        public static string Message_1 {
            get {
                return ResourceManager.GetString("Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card has been authorised and your payment received. You will shortly receive an email confirming your purchase. Thank you for your purchase.
        /// </summary>
        public static string Message_10 {
            get {
                return ResourceManager.GetString("Message_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy ! Auto Top Up option after your first transaction with Card.
        /// </summary>
        public static string Message_1000 {
            get {
                return ResourceManager.GetString("Message_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already registered with product,You can&apos;t add another product..
        /// </summary>
        public static string Message_1001 {
            get {
                return ResourceManager.GetString("Message_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product has been added to your account , but an error occured while adding credit or bundle to your account, Please contact customer services..
        /// </summary>
        public static string Message_1002 {
            get {
                return ResourceManager.GetString("Message_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred ,Please call our customer services team.
        /// </summary>
        public static string Message_1003 {
            get {
                return ResourceManager.GetString("Message_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of bundles for your subscription.
        /// </summary>
        public static string Message_101 {
            get {
                return ResourceManager.GetString("Message_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem establishing the connection or receving a response. Please contact our Customer Services..
        /// </summary>
        public static string Message_12 {
            get {
                return ResourceManager.GetString("Message_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount specified in the basket didn&apos;t match the total at checkout. Please try again.
        /// </summary>
        public static string Message_120 {
            get {
                return ResourceManager.GetString("Message_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction record creation failed..
        /// </summary>
        public static string Message_13 {
            get {
                return ResourceManager.GetString("Message_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number.
        /// </summary>
        public static string Message_14 {
            get {
                return ResourceManager.GetString("Message_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem establishing the connection/receiving a response. Please contact our Customer Services..
        /// </summary>
        public static string Message_15 {
            get {
                return ResourceManager.GetString("Message_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D secure validation failed..
        /// </summary>
        public static string Message_16 {
            get {
                return ResourceManager.GetString("Message_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem establishing the connection/receiving a response. Please contact our Customer Services..
        /// </summary>
        public static string Message_17 {
            get {
                return ResourceManager.GetString("Message_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation of your submission has failed..
        /// </summary>
        public static string Message_18 {
            get {
                return ResourceManager.GetString("Message_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Internal Server Error Occurred.
        /// </summary>
        public static string Message_19 {
            get {
                return ResourceManager.GetString("Message_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transaction was cancelled for security reasons as the top up process was left idle for a while..
        /// </summary>
        public static string Message_2 {
            get {
                return ResourceManager.GetString("Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully credited in the sum of £1..
        /// </summary>
        public static string Message_3 {
            get {
                return ResourceManager.GetString("Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Bundle limit reached. You cannot add more than 10 bundles.
        /// </summary>
        public static string Message_300 {
            get {
                return ResourceManager.GetString("Message_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has failed. Please retry again.
        /// </summary>
        public static string Message_34 {
            get {
                return ResourceManager.GetString("Message_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidMsisdnOnMiPay.
        /// </summary>
        public static string Message_351 {
            get {
                return ResourceManager.GetString("Message_351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have been unable to top up your account. Please try again later..
        /// </summary>
        public static string Message_4 {
            get {
                return ResourceManager.GetString("Message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This voucher is not recognised..
        /// </summary>
        public static string Message_5 {
            get {
                return ResourceManager.GetString("Message_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have been unable to top up your account. Please try again or contact our Customer Services..
        /// </summary>
        public static string Message_6 {
            get {
                return ResourceManager.GetString("Message_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment has not been authorised.
        /// </summary>
        public static string Message_601 {
            get {
                return ResourceManager.GetString("Message_601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string Message_602 {
            get {
                return ResourceManager.GetString("Message_602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyOrNullPayload.
        /// </summary>
        public static string Message_603 {
            get {
                return ResourceManager.GetString("Message_603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownError.
        /// </summary>
        public static string Message_608 {
            get {
                return ResourceManager.GetString("Message_608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction was found. There is no outcome to display.
        /// </summary>
        public static string Message_610 {
            get {
                return ResourceManager.GetString("Message_610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This voucher has expired..
        /// </summary>
        public static string Message_7 {
            get {
                return ResourceManager.GetString("Message_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line of address is required.
        /// </summary>
        public static string Message_700 {
            get {
                return ResourceManager.GetString("Message_700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        public static string Message_701 {
            get {
                return ResourceManager.GetString("Message_701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is required.
        /// </summary>
        public static string Message_702 {
            get {
                return ResourceManager.GetString("Message_702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string Message_703 {
            get {
                return ResourceManager.GetString("Message_703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post code is missing.
        /// </summary>
        public static string Message_704 {
            get {
                return ResourceManager.GetString("Message_704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required.
        /// </summary>
        public static string Message_705 {
            get {
                return ResourceManager.GetString("Message_705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a payment method below.
        /// </summary>
        public static string Message_706 {
            get {
                return ResourceManager.GetString("Message_706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is missing.
        /// </summary>
        public static string Message_707 {
            get {
                return ResourceManager.GetString("Message_707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is missing.
        /// </summary>
        public static string Message_708 {
            get {
                return ResourceManager.GetString("Message_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is missing.
        /// </summary>
        public static string Message_709 {
            get {
                return ResourceManager.GetString("Message_709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country was not recognised, please select a valid country.
        /// </summary>
        public static string Message_710 {
            get {
                return ResourceManager.GetString("Message_710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected payment method is invalid.
        /// </summary>
        public static string Message_711 {
            get {
                return ResourceManager.GetString("Message_711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was not understood.
        /// </summary>
        public static string Message_712 {
            get {
                return ResourceManager.GetString("Message_712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is missing.
        /// </summary>
        public static string Message_713 {
            get {
                return ResourceManager.GetString("Message_713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is required.
        /// </summary>
        public static string Message_714 {
            get {
                return ResourceManager.GetString("Message_714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t recognise that number. Please check that it belongs to the correct product.
        /// </summary>
        public static string Message_715 {
            get {
                return ResourceManager.GetString("Message_715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email seems to be invalid. Please try again.
        /// </summary>
        public static string Message_716 {
            get {
                return ResourceManager.GetString("Message_716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a top up before proceeding.
        /// </summary>
        public static string Message_717 {
            get {
                return ResourceManager.GetString("Message_717", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find that post code. Please check it and try again.
        /// </summary>
        public static string Message_718 {
            get {
                return ResourceManager.GetString("Message_718", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required.
        /// </summary>
        public static string Message_719 {
            get {
                return ResourceManager.GetString("Message_719", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string Message_720 {
            get {
                return ResourceManager.GetString("Message_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string Message_721 {
            get {
                return ResourceManager.GetString("Message_721", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an minimum of 8 characters for your password.
        /// </summary>
        public static string Message_722 {
            get {
                return ResourceManager.GetString("Message_722", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product for the order was missing. Please try again.
        /// </summary>
        public static string Message_723 {
            get {
                return ResourceManager.GetString("Message_723", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem processing your order. Please try again.
        /// </summary>
        public static string Message_724 {
            get {
                return ResourceManager.GetString("Message_724", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code used to activate the product is missing.
        /// </summary>
        public static string Message_726 {
            get {
                return ResourceManager.GetString("Message_726", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number provided was not valid.
        /// </summary>
        public static string Message_727 {
            get {
                return ResourceManager.GetString("Message_727", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has already registred this product. Please visit the page of your account if you wish to make any changes.
        /// </summary>
        public static string Message_729 {
            get {
                return ResourceManager.GetString("Message_729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in.
        /// </summary>
        public static string Message_730 {
            get {
                return ResourceManager.GetString("Message_730", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product does not exist.
        /// </summary>
        public static string Message_731 {
            get {
                return ResourceManager.GetString("Message_731", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of product does not exist.
        /// </summary>
        public static string Message_732 {
            get {
                return ResourceManager.GetString("Message_732", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to checkout. Please select a product first.
        /// </summary>
        public static string Message_733 {
            get {
                return ResourceManager.GetString("Message_733", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkout information are not correct. Please try again by selecting a product.
        /// </summary>
        public static string Message_734 {
            get {
                return ResourceManager.GetString("Message_734", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to make a purchase for an unregistred product. Please Add new Talk Home Mobile Account.
        /// </summary>
        public static string Message_735 {
            get {
                return ResourceManager.GetString("Message_735", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find that account. Have you registered that email address?.
        /// </summary>
        public static string Message_751 {
            get {
                return ResourceManager.GetString("Message_751", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unkwown error occurred while logging in. Please try again.
        /// </summary>
        public static string Message_753 {
            get {
                return ResourceManager.GetString("Message_753", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a temporary problem with the sign up. Please try again.
        /// </summary>
        public static string Message_755 {
            get {
                return ResourceManager.GetString("Message_755", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sign up was successful. Thank you for choosing Talk Home.
        /// </summary>
        public static string Message_756 {
            get {
                return ResourceManager.GetString("Message_756", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset link was sent to your email inbox if after a few minutes you do not receive it please check your spam in case it was mistakenly sent there.
        /// </summary>
        public static string Message_758 {
            get {
                return ResourceManager.GetString("Message_758", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset token has been validated. Set your new password below.
        /// </summary>
        public static string Message_760 {
            get {
                return ResourceManager.GetString("Message_760", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string Message_762 {
            get {
                return ResourceManager.GetString("Message_762", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for verifying your email. Please log in to access your Talk Home Mobile account.
        /// </summary>
        public static string Message_764 {
            get {
                return ResourceManager.GetString("Message_764", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot process a payment. Please verify your number.
        /// </summary>
        public static string Message_765 {
            get {
                return ResourceManager.GetString("Message_765", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a temporary problem when creating your account. Please try again.
        /// </summary>
        public static string Message_767 {
            get {
                return ResourceManager.GetString("Message_767", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a temporary problem when verifying your account. Please try again.
        /// </summary>
        public static string Message_768 {
            get {
                return ResourceManager.GetString("Message_768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was successfully added to your account.
        /// </summary>
        public static string Message_769 {
            get {
                return ResourceManager.GetString("Message_769", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully added to the basket.
        /// </summary>
        public static string Message_771 {
            get {
                return ResourceManager.GetString("Message_771", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem adding that product to the basket. Please try again.
        /// </summary>
        public static string Message_772 {
            get {
                return ResourceManager.GetString("Message_772", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully removed from the basket.
        /// </summary>
        public static string Message_773 {
            get {
                return ResourceManager.GetString("Message_773", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem removing that product from the basket.
        /// </summary>
        public static string Message_774 {
            get {
                return ResourceManager.GetString("Message_774", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basket is now empty.
        /// </summary>
        public static string Message_775 {
            get {
                return ResourceManager.GetString("Message_775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was not valid. Please provide a valid identifier.
        /// </summary>
        public static string Message_776 {
            get {
                return ResourceManager.GetString("Message_776", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That product cannnot be added to the basket as it belongs to a different category. Please clear or checkout the current basket first.
        /// </summary>
        public static string Message_777 {
            get {
                return ResourceManager.GetString("Message_777", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is not yet registered.
        /// </summary>
        public static string Message_778 {
            get {
                return ResourceManager.GetString("Message_778", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid number.
        /// </summary>
        public static string Message_779 {
            get {
                return ResourceManager.GetString("Message_779", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not in the valid range.
        /// </summary>
        public static string Message_780 {
            get {
                return ResourceManager.GetString("Message_780", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a balance threshold.
        /// </summary>
        public static string Message_781 {
            get {
                return ResourceManager.GetString("Message_781", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The auto top up was successfully configured.
        /// </summary>
        public static string Message_782 {
            get {
                return ResourceManager.GetString("Message_782", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The auto renewal was successfully configured.
        /// </summary>
        public static string Message_783 {
            get {
                return ResourceManager.GetString("Message_783", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has  exceeded SIM orders for this account. Please contact Customer Services if you require another SIM.
        /// </summary>
        public static string Message_784 {
            get {
                return ResourceManager.GetString("Message_784", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient credit to add this product to the basket. Checkout with current basket products.
        /// </summary>
        public static string Message_785 {
            get {
                return ResourceManager.GetString("Message_785", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient credit on your mobile account to make the transfer.
        /// </summary>
        public static string Message_786 {
            get {
                return ResourceManager.GetString("Message_786", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email addresses do no match.
        /// </summary>
        public static string Message_787 {
            get {
                return ResourceManager.GetString("Message_787", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This voucher is invalid..
        /// </summary>
        public static string Message_8 {
            get {
                return ResourceManager.GetString("Message_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to process your payment. Please try again, if the problem persists, contact our Customer Service..
        /// </summary>
        public static string Message_9 {
            get {
                return ResourceManager.GetString("Message_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points are unsufficient.
        /// </summary>
        public static string Message_954 {
            get {
                return ResourceManager.GetString("Message_954", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error redeeming the points. Please try again.
        /// </summary>
        public static string Message_955 {
            get {
                return ResourceManager.GetString("Message_955", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a temporary problem when registering that product. Please try again.
        /// </summary>
        public static string Message_975 {
            get {
                return ResourceManager.GetString("Message_975", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The details provided were invalid. Please double check them and try again.
        /// </summary>
        public static string Message_976 {
            get {
                return ResourceManager.GetString("Message_976", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with those credentials has already been registred.
        /// </summary>
        public static string Message_977 {
            get {
                return ResourceManager.GetString("Message_977", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That phone number or PIN didn&apos;t match our records. Please double check them and try again.
        /// </summary>
        public static string Message_978 {
            get {
                return ResourceManager.GetString("Message_978", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That phone number or PUK code didn&apos;t match our records. Please double check them and try again.
        /// </summary>
        public static string Message_979 {
            get {
                return ResourceManager.GetString("Message_979", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to save that password. Please try again.
        /// </summary>
        public static string Message_980 {
            get {
                return ResourceManager.GetString("Message_980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification token was invalid.
        /// </summary>
        public static string Message_981 {
            get {
                return ResourceManager.GetString("Message_981", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the email address. Please ensure the email address is already registred with us.
        /// </summary>
        public static string Message_982 {
            get {
                return ResourceManager.GetString("Message_982", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password provided do not match our records.
        /// </summary>
        public static string Message_983 {
            get {
                return ResourceManager.GetString("Message_983", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a link via email to your inbox to confirm your account. Please activate your account by following that link.
        /// </summary>
        public static string Message_984 {
            get {
                return ResourceManager.GetString("Message_984", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were too many failed login attempts. Please try again later.
        /// </summary>
        public static string Message_985 {
            get {
                return ResourceManager.GetString("Message_985", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t verify your details. Please try following the link in the email you received again.
        /// </summary>
        public static string Message_986 {
            get {
                return ResourceManager.GetString("Message_986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has already been verified. Please log in.
        /// </summary>
        public static string Message_987 {
            get {
                return ResourceManager.GetString("Message_987", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email address already exists, please log in.
        /// </summary>
        public static string Message_988 {
            get {
                return ResourceManager.GetString("Message_988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code was invalid.
        /// </summary>
        public static string Message_993 {
            get {
                return ResourceManager.GetString("Message_993", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid post code. Please try again.
        /// </summary>
        public static string Message_994 {
            get {
                return ResourceManager.GetString("Message_994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact customer services to validate the account for this PIN.
        /// </summary>
        public static string Message_995 {
            get {
                return ResourceManager.GetString("Message_995", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sim associated to your account. Please register one first to port.
        /// </summary>
        public static string Message_996 {
            get {
                return ResourceManager.GetString("Message_996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim Order Successful but Port In request failed..
        /// </summary>
        public static string Message_997 {
            get {
                return ResourceManager.GetString("Message_997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service timeout (no response from Mi-Pay core).
        /// </summary>
        public static string Message_W1 {
            get {
                return ResourceManager.GetString("Message_W1", resourceCulture);
            }
        }
    }
}
