//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public long BranchID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<long> regionID { get; set; }
        public Nullable<long> BranchID_Old { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<long> RGM { get; set; }
        public Nullable<long> AreaCoach { get; set; }
        public Nullable<long> BusniessHead { get; set; }
        public Nullable<long> AsstManagerDelivery { get; set; }
        public Nullable<long> DeliveryHead { get; set; }
        public Nullable<long> ManagerCC { get; set; }
        public Nullable<int> TimeExtension { get; set; }
        public string email { get; set; }
        public Nullable<int> bStatus { get; set; }
        public Nullable<int> tempStatus { get; set; }
        public string statusReasons { get; set; }
        public string extReasons { get; set; }
        public string ClosingTime { get; set; }
        public Nullable<long> SupplyChainManager { get; set; }
        public Nullable<long> SupplyChainTeam { get; set; }
        public Nullable<long> ConcernCallCenter { get; set; }
        public Nullable<long> locationIdDT { get; set; }
        public string addressDT { get; set; }
        public Nullable<long> DeliveryArea { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string ClosingMon { get; set; }
        public string ClosingTue { get; set; }
        public string ClosingWed { get; set; }
        public string ClosingThu { get; set; }
        public string ClosingFri { get; set; }
        public string ClosingSat { get; set; }
        public string ClosingSun { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string MidnightTime { get; set; }
        public Nullable<long> FoodPandaBranchId { get; set; }
        public Nullable<int> isEnabledForRiderApp { get; set; }
        public string gesCode { get; set; }
        public Nullable<int> isAutoDelivery { get; set; }
        public Nullable<int> perKMRate { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
        public string Terminal { get; set; }
        public string serverUsername { get; set; }
        public string serverPassword { get; set; }
        public string creditMode { get; set; }
        public string foodPandaCode { get; set; }
        public string posStoreNo { get; set; }
        public Nullable<int> isDynamicPosEnabled { get; set; }
        public string OpeningTime { get; set; }
        public string walletPassword { get; set; }
        public Nullable<int> isWalletPasswordChanged { get; set; }
        public Nullable<int> DynamicApi { get; set; }
        public Nullable<int> isDynamicPullEnabled { get; set; }
        public Nullable<int> IsStagingEnabled { get; set; }
        public Nullable<int> EnabledForVentureDive { get; set; }
        public Nullable<int> EnabledForFPHero { get; set; }
        public string PolyGon { get; set; }
        public string Terminal_P { get; set; }
        public string serverUsername_P { get; set; }
        public string serverPassword_P { get; set; }
        public string DatabaseName_P { get; set; }
        public string posStoreNo_P { get; set; }
        public string ServerName_P { get; set; }
        public string creditcard { get; set; }
        public string OpeningMon { get; set; }
        public string OpeningTue { get; set; }
        public string OpeningWed { get; set; }
        public string OpeningThu { get; set; }
        public string OpeningFri { get; set; }
        public string OpeningSat { get; set; }
        public string OpeningSun { get; set; }
        public Nullable<int> autoDispatchDistance { get; set; }
        public Nullable<int> autoAssignDistacne { get; set; }
        public Nullable<int> orderLimit { get; set; }
        public Nullable<int> orderAssignTime { get; set; }
        public Nullable<int> simplexEnabled { get; set; }
        public string PickupClosingMon { get; set; }
        public string PickupClosingTue { get; set; }
        public string PickupClosingWed { get; set; }
        public string PickupClosingThu { get; set; }
        public string PickupClosingFri { get; set; }
        public string PickupClosingSat { get; set; }
        public string PickupClosingSun { get; set; }
        public Nullable<bool> updatePaymentMode { get; set; }
        public string TaxAuthority { get; set; }
        public Nullable<long> TaxRate { get; set; }
        public Nullable<long> CashTaxRate { get; set; }
        public Nullable<long> CreditTaxRate { get; set; }
        public Nullable<long> POSID { get; set; }
        public string IdentNoFBR { get; set; }
        public string BranchNameFBR { get; set; }
        public string CodeFBR { get; set; }
        public string TokenFBR { get; set; }
        public string PCTCode { get; set; }
        public Nullable<bool> isTaxWorkingEnabled { get; set; }
        public Nullable<int> DynamicPosRegionId { get; set; }
        public Nullable<int> EnabledForFPAutoAcceptance { get; set; }
    }
}
