//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        public long DeliveryOrderID { get; set; }
        public Nullable<long> OrderNo { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> OrderStatus { get; set; }
        public Nullable<long> PromotionID { get; set; }
        public Nullable<long> HundredthOrderCount { get; set; }
        public string DeliveryAddress { get; set; }
        public string Instruction { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> AgentID { get; set; }
        public Nullable<System.DateTime> BookedDateTime { get; set; }
        public Nullable<long> ReceivedByID { get; set; }
        public Nullable<System.DateTime> ReceivedByDateTime { get; set; }
        public Nullable<long> DispatchedByID { get; set; }
        public Nullable<System.DateTime> DispatchedDateTime { get; set; }
        public Nullable<long> FinalStatusByID { get; set; }
        public Nullable<System.DateTime> FinalStatusDateTIme { get; set; }
        public Nullable<long> BranchRiderID { get; set; }
        public Nullable<long> PartialRejectAmount { get; set; }
        public string PartialRejectComment { get; set; }
        public Nullable<long> Location { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<long> CancelAgentID { get; set; }
        public string CancelComment { get; set; }
        public Nullable<bool> BranchLock { get; set; }
        public Nullable<bool> takeAway { get; set; }
        public Nullable<long> ServiceCharges { get; set; }
        public string timeRequired { get; set; }
        public string OrderThrough { get; set; }
        public string Complaints { get; set; }
        public Nullable<bool> isModified { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public string ComplaintComments { get; set; }
        public string ComplaintCategory { get; set; }
        public Nullable<int> ComplaintStatus { get; set; }
        public Nullable<long> ComplaintStatusBy { get; set; }
        public Nullable<System.DateTime> ComplaintStatusDateTIme { get; set; }
        public Nullable<bool> AddressDisable { get; set; }
        public Nullable<long> DonationAmount { get; set; }
        public Nullable<bool> IsPusshToPOS { get; set; }
        public Nullable<bool> deliverOnBranch { get; set; }
        public Nullable<int> OfflineOrder { get; set; }
        public Nullable<long> DiscountPercent { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<long> DeliveryOrderIDTemp { get; set; }
        public Nullable<int> cancelCheckOnBranch { get; set; }
        public string customerAddressDisableComment { get; set; }
        public string ConfirmRejectionComment { get; set; }
        public Nullable<int> isConfirmRejection { get; set; }
        public Nullable<long> ConfirmRejectionBy { get; set; }
        public Nullable<System.DateTime> ConfirmRejectionDate { get; set; }
        public string CLI { get; set; }
        public Nullable<System.DateTime> SamsungRiderDate { get; set; }
        public Nullable<System.DateTime> SamsungDeliveryDate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<long> AppRiderId { get; set; }
        public Nullable<long> AppOrderStatus { get; set; }
        public Nullable<System.DateTime> AppOrderStatusDate { get; set; }
        public Nullable<System.DateTime> AppRiderAssignDate { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string SamsungAPIResponse { get; set; }
        public Nullable<bool> isPushToSamsung { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<double> rating2 { get; set; }
        public Nullable<double> rating3 { get; set; }
        public string ratingComment { get; set; }
        public Nullable<long> HowDoYouKnow { get; set; }
        public string DistanceByRider { get; set; }
        public Nullable<bool> AutoTransfer { get; set; }
        public Nullable<bool> isPushToRiderApp { get; set; }
        public Nullable<int> isPickup { get; set; }
        public Nullable<System.DateTime> reachedDateTime { get; set; }
        public string deliveryTime { get; set; }
        public string dynamicApiResponseCreate { get; set; }
        public Nullable<System.DateTime> dynamicApiDateTime { get; set; }
        public string dynamicApiResponseUpdate { get; set; }
        public string PaymentModeOld { get; set; }
        public Nullable<int> isChargeToFoodPanda { get; set; }
        public string chargeToFoodPandaReason { get; set; }
        public Nullable<int> isPaymentModeChange { get; set; }
        public string FPOrderId { get; set; }
        public Nullable<System.DateTime> NEW_TIME { get; set; }
        public Nullable<System.DateTime> RECEIVED_TIME { get; set; }
        public Nullable<System.DateTime> WAITING_FOR_TRANSPORT_TIME { get; set; }
        public Nullable<System.DateTime> ASSIGNED_TO_TRANSPORT_TIME { get; set; }
        public Nullable<System.DateTime> COURIER_ACCEPTED_DELIVERY_TIME { get; set; }
        public Nullable<System.DateTime> NEAR_VENDOR_TIME { get; set; }
        public Nullable<System.DateTime> PICKED_UP_TIME { get; set; }
        public Nullable<System.DateTime> COURIER_LEFT_VENDOR_TIME { get; set; }
        public Nullable<System.DateTime> NEAR_CUSTOMER_TIME { get; set; }
        public Nullable<System.DateTime> DELIVERED_TIME { get; set; }
        public Nullable<System.DateTime> DELAYED_TIME { get; set; }
        public Nullable<System.DateTime> CANCELLED_TIME { get; set; }
        public Nullable<System.DateTime> fpAssignDatetime { get; set; }
        public string VentureDiveOrderId { get; set; }
        public Nullable<int> cancelByKFC { get; set; }
        public string PaymentReversalId { get; set; }
        public string ActionId { get; set; }
        public string PaymentReversalAction { get; set; }
        public string PaymentReversalDateTime { get; set; }
        public Nullable<System.DateTime> PaymentReversalCreateDate { get; set; }
        public string ARN { get; set; }
        public Nullable<System.DateTime> CancelDateTime { get; set; }
        public Nullable<int> isCancellationSMSSent { get; set; }
        public Nullable<System.DateTime> CanceledDateTime { get; set; }
        public Nullable<System.DateTime> RejectedDateTime { get; set; }
        public Nullable<int> isthroughriderportal { get; set; }
        public Nullable<int> CancelByKFCMiddelWear { get; set; }
        public string FPCancelationReason { get; set; }
        public string FBR_BRA_InvNo { get; set; }
        public string FBR_Reversal_InvNo { get; set; }
        public Nullable<decimal> TotalTaxCharged { get; set; }
        public Nullable<decimal> TotalDiscountFBR { get; set; }
        public Nullable<long> TaxPercentageFBR { get; set; }
        public Nullable<long> TaxAmountFBR { get; set; }
        public Nullable<long> TotalAmountExclusiveofTaxFBR { get; set; }
        public Nullable<bool> FlagPandaProVoucher_Partial { get; set; }
        public Nullable<long> ServiceChargesCreditOrdersForTax { get; set; }
        public Nullable<long> ServiceChargesExclusiveofTax { get; set; }
        public Nullable<long> ServiceChargesTaxCharged { get; set; }
        public Nullable<int> isTaxCalculatedFP { get; set; }
    }
}
