//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrderTemp
    {
        public long DeliveryOrderID { get; set; }
        public Nullable<long> OnlineDeleiveryOrderID { get; set; }
        public Nullable<long> OrderNo { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> OrderStatus { get; set; }
        public Nullable<long> PromotionID { get; set; }
        public Nullable<long> HundredthOrderCount { get; set; }
        public string DeliveryAddress { get; set; }
        public string Instruction { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> AgentID { get; set; }
        public Nullable<System.DateTime> BookedDateTime { get; set; }
        public Nullable<long> ReceivedByID { get; set; }
        public Nullable<System.DateTime> ReceivedByDateTime { get; set; }
        public Nullable<long> DispatchedByID { get; set; }
        public Nullable<System.DateTime> DispatchedDateTime { get; set; }
        public Nullable<long> FinalStatusByID { get; set; }
        public Nullable<System.DateTime> FinalStatusDateTIme { get; set; }
        public Nullable<long> BranchRiderID { get; set; }
        public Nullable<long> PartialRejectAmount { get; set; }
        public string PartialRejectComment { get; set; }
        public Nullable<long> Location { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<long> CancelAgentID { get; set; }
        public string CancelComment { get; set; }
        public Nullable<bool> BranchLock { get; set; }
        public Nullable<bool> takeAway { get; set; }
        public Nullable<long> ServiceCharges { get; set; }
        public string timeRequired { get; set; }
        public string OrderThrough { get; set; }
        public string Complaints { get; set; }
        public Nullable<bool> isModified { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public string ComplaintComments { get; set; }
        public string ComplaintCategory { get; set; }
        public Nullable<int> ComplaintStatus { get; set; }
        public Nullable<long> ComplaintStatusBy { get; set; }
        public Nullable<System.DateTime> ComplaintStatusDateTIme { get; set; }
        public Nullable<bool> AddressDisable { get; set; }
        public Nullable<long> DonationAmount { get; set; }
        public Nullable<int> TempStatus { get; set; }
        public string ItemDetailArray { get; set; }
        public string CIN { get; set; }
        public Nullable<long> Discount { get; set; }
        public string VoucherNo { get; set; }
        public string cancelOrderTempCommnet { get; set; }
        public string cancelOrderTempReason { get; set; }
        public Nullable<int> isAccept { get; set; }
        public Nullable<int> regionID { get; set; }
        public string OrderCity { get; set; }
        public Nullable<bool> isAssigned { get; set; }
        public Nullable<long> cancelStatus { get; set; }
        public Nullable<long> confirmCancelAgentID { get; set; }
        public Nullable<System.DateTime> confirmCancelDate { get; set; }
        public string cancelOrderTempCommnetForward { get; set; }
        public string cancelOrderTempReasonForward { get; set; }
        public string API_Response { get; set; }
        public string Website { get; set; }
        public string voucherName { get; set; }
        public string description { get; set; }
        public Nullable<long> voucherAmount { get; set; }
        public string FB_API_ResponseTime { get; set; }
        public string onlineTransactionDetails { get; set; }
        public Nullable<int> isPickup { get; set; }
        public Nullable<int> isBranchAccept { get; set; }
        public Nullable<int> branchAcceptStatus { get; set; }
        public string branchNotAcceptReason { get; set; }
        public Nullable<long> acceptStatusBy { get; set; }
        public Nullable<System.DateTime> acceptStatusAt { get; set; }
        public string isThroughApp { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string OrderType { get; set; }
        public string fpToken { get; set; }
        public string FBR_BRA_InvNo { get; set; }
        public Nullable<decimal> TotalTaxCharged { get; set; }
        public Nullable<long> TaxPercentageFBR { get; set; }
        public Nullable<long> TaxAmountFBR { get; set; }
        public Nullable<long> TotalAmountExclusiveofTaxFBR { get; set; }
        public Nullable<long> ServiceChargesCreditOrdersForTax { get; set; }
        public Nullable<long> ServiceChargesExclusiveofTax { get; set; }
        public Nullable<long> ServiceChargesTaxCharged { get; set; }
    }
}
