//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrderDetail
    {
        public long DeliveryOrderDetailID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> FamilyID { get; set; }
        public Nullable<long> MenuItemID { get; set; }
        public Nullable<long> MenuPrice { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<bool> IsWithCheze { get; set; }
        public Nullable<bool> IsFrenchFriesUpSize { get; set; }
        public Nullable<bool> IsDrinkUpsize { get; set; }
        public Nullable<long> MenuFamilyMeasureID { get; set; }
        public string instruction { get; set; }
        public Nullable<long> ItemTotalAmountforTax { get; set; }
        public Nullable<long> ItemAmountExcofTax { get; set; }
        public Nullable<long> ItemTaxRate { get; set; }
        public Nullable<long> ItemTaxCharged { get; set; }
        public Nullable<long> ServiceChargesCreditOrdersForTax { get; set; }
        public Nullable<long> ServiceChargesExclusiveofTax { get; set; }
        public Nullable<long> ServiceChargesTaxCharged { get; set; }
    }
}
