//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodPandaPayload
    {
        public long Id { get; set; }
        public string Payload { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public string branchId { get; set; }
        public Nullable<System.DateTime> requestStartTime { get; set; }
        public Nullable<System.DateTime> requestEndTime { get; set; }
        public string totalDuration { get; set; }
        public string response { get; set; }
        public string ServerIP { get; set; }
        public string apiType { get; set; }
        public string orderNo { get; set; }
    }
}
