//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FpAcknowledgementQueue
    {
        public long Id { get; set; }
        public Nullable<long> DeliveryOrderIdTemp { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> ud { get; set; }
        public Nullable<System.DateTime> ProcessingStartTime { get; set; }
        public Nullable<System.DateTime> ProcessingEndTime { get; set; }
        public string TotalProcessingTime { get; set; }
        public string Response { get; set; }
        public Nullable<int> nooftries { get; set; }
        public string AccessToken { get; set; }
    }
}
