//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long ID { get; set; }
        public Nullable<long> FamilyID { get; set; }
        public Nullable<long> MenuItemID { get; set; }
        public Nullable<long> FamilyMeasureID { get; set; }
        public Nullable<long> GrossPrice { get; set; }
        public Nullable<long> GST { get; set; }
        public Nullable<long> MenuPrice { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<long> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<long> RecStatusID { get; set; }
        public string VersionNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string barcode { get; set; }
        public string barcodeFP { get; set; }
        public Nullable<bool> isDisabled { get; set; }
        public Nullable<bool> isDisabledTemp { get; set; }
        public Nullable<bool> IsMidnight { get; set; }
        public string MidnightTime { get; set; }
        public string ImagePath { get; set; }
        public string pos_itemCode { get; set; }
    }
}
